# Generated by Django 4.1.5 on 2023-01-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_Title', models.CharField(max_length=50)),
                ('news_Author', models.CharField(max_length=50)),
                ('news_Label', models.BooleanField(default=False)),
                ('news_Text', models.CharField(max_length=5000)),
            ],
        ),
    ]
