# Generated by Django 4.1.5 on 2023-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorgu', '0002_news_news_subject_news_news_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Algo',
            field=models.CharField(default='RandomForestClassifier', max_length=50),
        ),
    ]
