# Generated by Django 4.1.5 on 2023-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorgu', '0003_news_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_Text',
            field=models.CharField(default='', max_length=75),
        ),
    ]
