# Generated by Django 4.1.5 on 2023-01-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorgu', '0004_news_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_Text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
