# Generated by Django 4.1.5 on 2023-01-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorgu', '0005_alter_news_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='DT_Label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='DT_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='GBC_Label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='GBC_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='LR_Label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='LR_Score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='NB_Label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='NB_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='RFC_Label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='RFC_Score',
            field=models.IntegerField(default=0),
        ),
    ]
