# Generated by Django 4.1.5 on 2023-01-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorgu', '0007_alter_news_dt_score_alter_news_gbc_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Algo',
        ),
    ]
